blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<tag_slug>/', views.post_list, name='post_list_by_tag'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
        views.post_detail, name='post_detail'),
    path('<post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('privacy-policy-and-disclaimer/', views.privacy_disclaimer, name="privacy-disclaimer"),
    path('gdpr-privacy-policy/', views.gdpr_policy, name="gdpr-policy")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, 
                                    name='django.contrib.sitemaps.views.sitemap'),
]
if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL,
 document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                        self).get_queryset().filter(status='published')

class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    image = models.ImageField(upload_to='images/%Y/%m/%d/', blank=True)
    author = models.ForeignKey(User,
                            on_delete=models.CASCADE,
                            related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                            choices=STATUS_CHOICES,
                            default='draft')
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title
                                                                        
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[self.publish.year,
                        self.publish.month,
                        self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                            on_delete=models.CASCADE,
                            related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__ (self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={
                                                                    'placeholder': 'Name',
                                                                    'id': 'sharepost-name',
                                                                    'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
                                                        'placeholder': 'Email',
                                                        'id': 'sharepost-email',
                                                        'class': 'form-control'}))
    to = forms.EmailField(widget=forms.EmailInput(attrs={
                                                    'placeholder': 'To',
                                                    'id': 'sharepost-to',
                                                    'class': 'form-control'}))
    comments = forms.CharField(required=False,
                                widget=forms.Textarea(attrs={
                                                        'placeholder': 'Comments',
                                                        'id': 'sharepost-comments',
                                                        'class': 'form-control'}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'name': forms.TextInput(attrs={'id': 'comment-name',
                                            'class': 'form-control',
                                            'placeholder': 'Name'}),
            'email': forms.EmailInput(attrs={'id': 'comment-email',
                                                'class': 'form-control',
                                                'placeholder': 'Email'}),
            'body': forms.Textarea(attrs={'id': 'comment-body',
                                            'class': 'form-control',
                                            'placeholder': 'Comment'})
        }


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.views.decorators.csrf import csrf_exempt



def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    query = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    if 'search' in request.GET:
        if len(request.GET.get('search')) > 0:
            query = request.GET.get('search')
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            object_list = Post.published.annotate(search=search_vector,
                                                    rank=SearchRank(search_vector, search_query)
                                                    ).filter(search=search_query).order_by('-rank')


    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    print(page)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page Is not an Integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of ranger deliver last page of the result
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html', {'page': page,
                                                'posts': posts,
                                                'tag': tag,
                                                'searchquery': query})


"""
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 1
    template_name = 'blog/post/list.html'
"""

@csrf_exempt
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None
    downloadlink = None
    if request.method == 'POST':
        # A comment was posted
        downloadlink = request.POST.get("downloadlink")
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment object don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similiar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')
    return render(request, 'blog/post/detail.html', {'post': post,
                                                    'comments': comments,
                                                    'new_comment': new_comment,
                                                    'comment_form': comment_form,
                                                    'similar_posts':similar_posts,
                                                     'downloadlink': downloadlink})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ...send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends your read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                        f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'nfsrivalsuploaded@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                        'form': form,
                                                        'sent':sent})


def privacy_disclaimer(request):
    return render(request, 'blog/privacy-policy.html')


def gdpr_policy(request):
    return render(request, 'blog/gdpr-policy.html')

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <section class="site-section py-lg">
        {% if downloadlink %}
            <div class="row begin-countdown">
              <div class="col-md-12 text-center">
                  <a href="#showsecond" style="display:none;" id="firstlink" class="btn btn-outline-dark btn-lg " role="button" aria-disabled="true">Click Here</a>

                  </br>
                <progress value="10" max="10" id="pageBeginCountdown"></progress>
                  <button type="button" class="btn btn-primary btn-lg btn-block">Download link ready in <span id="pageBeginCountdownText">10 </span> seconds</button>
                  </br>
              </div>
            </div>
        {% endif %}

      <div class="container">
        {% if downloadlink %}
          <p>{{ downloadlink }}</p>
          {% endif %}
        <div class="row blog-entries element-animate fadeInUp element-animated">

          <div class="col-md-12 col-lg-8 main-content">
            <img src="{{ post.image.url }}" alt="Image" class="img-fluid mb-5">
              <div id="showsecond"></div>
             <div class="post-meta">
                <span class="mr-2">{{ post.publish }}</span>
                <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
              </div>
              <h1 class="mb-4">{{ post.title }}</h1>
               {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="category mb-5">{{ tag }}</a>
                {% endfor %}

            <div class="post-content-body">
                <a href="{{ downloadlink }}" style="display:none;" id="secondlink" class="btn btn-primary btn-lg" role="button" aria-disabled="true">Download</a>
                <p>{{ post.body|markdown }}</p>
            </div>


            <div class="pt-5">
                {% with comments.count as total_comments %}
                    <h3 class="mb-5">{{ total_comments }} comment{{ total_comments|pluralize }}</h3>
                {% endwith %}
              <ul class="comment-list">
                {% for comment in comments %}
                    <li class="comment">
                      <div class="vcard">
                        <!--<img src="images/person_1.jpg" alt="Image placeholder">-->
                      </div>
                      <div class="comment-body">
                        <h3>{{ comment.name }}</h3>
                        <div class="meta">{{ comment.created }}</div>
                        <p>{{ comment.body|linebreaks }}</p>
                      </div>
                    </li>
                  {% empty %}
                    <p>There are no comments yet.</p>
                  {% endfor %}
              </ul>
              <!-- END comment-list -->


              <div class="comment-form-wrap pt-5">
                  {% if new_comment %}
                    <h2>Your comment has been added.</h2>
                  {% else %}
                    <h3 class="mb-5">Leave a comment</h3>

                <form method="post" class="p-5 bg-light">
                    {% for field in comment_form %}
                        <div class="form-group">
                            {{ field }}
                        </div>
                    {% endfor %}
                    {% csrf_token %}
                    <p><input class="btn btn-secondary" type="submit" value="Add comment"></p>
                </form>
                  {% endif %}
              </div>
            </div>

          </div>

          <!-- END main-content -->

          <div class="col-md-12 col-lg-4 sidebar">
            <div class="sidebar-box search-form-wrap">
              <form action="#" class="search-form">
                <div class="form-group">
                  <span class="icon fa fa-search"></span>
                  <input type="text" class="form-control" id="s" placeholder="Type a keyword and hit enter">
                </div>
              </form>
            </div>
            <!-- END sidebar-box -->

            <div class="sidebar-box">
              <div class="bio text-center">
                <!--<img src="images/person_2.jpg" alt="Image Placeholder" class="img-fluid">-->
                <div class="bio-body">
                  <h2>Craig David</h2>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem facilis sunt repellendus excepturi beatae porro debitis voluptate nulla quo veniam fuga sit molestias minus.</p>
                  <p><a href="#" class="btn btn-primary btn-sm rounded">Read my bio</a></p>
                  <p class="social">
                    <a href="#" class="p-2"><span class="fa fa-facebook"></span></a>
                    <a href="#" class="p-2"><span class="fa fa-twitter"></span></a>
                    <a href="#" class="p-2"><span class="fa fa-instagram"></span></a>
                    <a href="#" class="p-2"><span class="fa fa-youtube-play"></span></a>
                  </p>
                </div>
              </div>
            </div>
            <!-- END sidebar-box -->
             <div class="sidebar-box">
                    <h3 class="heading">Popular Posts</h3>
                    <div class="post-entry-sidebar">
                      <ul>
                          {% get_most_commented_posts as most_commented_post %}
                                {% for post in most_commented_post %}
                                    <li>
                                      <a href="{{ post.get_absolute_url }}">
                                        <img src="{% if post.image %}{{ post.image.url }}{% else %}images/person_1.jpg{% endif %}" alt="Image placeholder" class="mr-4">
                                        <div class="text">
                                          <h4>{{ post.title }}</h4>
                                          <div class="post-meta">
                                            <span class="mr-2">{{ post.publish }}</span>
                                          </div>
                                        </div>
                                      </a>
                                    </li>
                                {% endfor %}
                      </ul>
                    </div>
                  </div>
            <!-- END sidebar-box -->

            <div class="sidebar-box">
              <h3 class="heading">Tags</h3>
              <ul class="tags">
                  {% for tag in post.tags.all %}
                    <li><a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag }}</a></li>
                  {% endfor %}
              </ul>
            </div>
          </div>
          <!-- END sidebar -->

        </div>
      </div>
    </section>

    <section class="py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2 class="mb-3 ">Related Post</h2>
          </div>
        </div>
        <div class="row">
            {% for post in similar_posts %}
              <div class="col-md-6 col-lg-4">
                <a href="{{ post.get_absolute_url }}" class="a-block sm d-flex align-items-center height-md" style="background-image: url('{% if post.image %}{{ post.image.url }}{% else %}images/person_1.jpg{% endif %}'); ">
                  <div class="text">
                    <div class="post-meta">
                      <span class="category">Lifestyle</span>
                      <span class="mr-2">March 15, 2018 </span>
                      <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                    </div>
                    <h3>{{ post.title }}</h3>
                  </div>
                </a>
              </div>
            {% empty %}
                There are no similar posts yet.
            {% endfor %}
        </div>
      </div>

    </section>

{% endblock %}

{% block downloadlink %}
    {% if  downloadlink %}

          ProgressCountdown(10, 'pageBeginCountdown', 'pageBeginCountdownText').then(value => alert(`Page has started: ${value}.`));

          function ProgressCountdown(timeleft, bar, text) {
            return new Promise((resolve, reject) => {
              var countdownTimer = setInterval(() => {
                timeleft--;

                document.getElementById(bar).value = timeleft;
                document.getElementById(text).textContent = timeleft;

                if (timeleft <= 0) {
                  clearInterval(countdownTimer);
                  $("#firstlink").show();
                  $("#secondlink").show();
                }
              }, 1000);
            });
          }
    {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
          <li>
            <a href="{{ post.get_absolute_url }}">
              <img src="{% if post.image %}{{ post.image.url }}{% else %}images/person_1.jpg{% endif %}" alt="Image placeholder" class="mr-4">
              <div class="text">
                <h4>{{ post.title }}</h4>
                <div class="post-meta">
                  <span class="mr-2">{{ post.publish }}</span> •
                  <span class="ml-2"><span class="fa fa-comments"></span>{{ post.comments.all.count }}</span>
                </div>
              </div>
            </a>
          </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}

{% block content %}
    <section class="site-section py-sm">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <h2 class="mb-4">Latest Posts</h2>
            </div>
          </div>
          <div class="row blog-entries">
            <div class="col-md-12 col-lg-8 main-content">
              <div class="row">
                {% if searchquery %}
                    <h2>Posts containing "{{ searchquery }}"</h2>
                    {% if not posts %}
                        <p>0 posts found</p>
                    {% endif %}
                {% endif %}
                {% if tag %}
                    <h2>Posts tagged with "{{ tag.name }}"</h2>
                {% endif %}
                {% for post in posts %}
                    <div class="col-md-6">
                      <a href="{{ post.get_absolute_url }}" class="blog-entry element-animate fadeIn element-animated" data-animate-effect="fadeIn">
                        <img src="{% if post.image %}{{ post.image.url }}{% else %}images/person_1.jpg{% endif %}" alt="Image placeholder">
                        <div class="blog-content-body">
                          <div class="post-meta">
                            <span class="author mr-2">{{ post.author }}</span>•
                            <span class="mr-2">{{ post.publish }}</span> •
                            <span class="ml-2"><span class="fa fa-comments"></span>{{ post.comments.all.count }}</span>
                          </div>
                          <h2>{{ post.title }}</h2>
                        </div>
                      </a>
                    </div>
                  {% endfor %}

              </div>

                {% include "pagination.html" with page=posts %}

            </div>

            <!-- END main-content -->
              <div class="col-md-12 col-lg-4 sidebar">
                  <div class="sidebar-box search-form-wrap">
                    <form action="#" class="search-form">
                      <div class="form-group">
                        <span class="icon fa fa-search"></span>
                        <input type="text" class="form-control" id="s" placeholder="Type a keyword and hit enter">
                      </div>
                    </form>
                  </div>
                  <!-- END sidebar-box -->
                  <div class="sidebar-box">
                    <h3 class="heading">Popular Posts</h3>
                    <div class="post-entry-sidebar">
                      <ul>
                          {% get_most_commented_posts as most_commented_post %}
                                {% for post in most_commented_post %}
                                    <li>
                                      <a href="{{ post.get_absolute_url }}">
                                        <img src="{% if post.image %}{{ post.image.url }}{% else %}images/person_1.jpg{% endif %}" alt="Image placeholder" class="mr-4">
                                        <div class="text">
                                          <h4>{{ post.title }}</h4>
                                          <div class="post-meta">
                                            <span class="mr-2">{{ post.publish }}</span>
                                          </div>
                                        </div>
                                      </a>
                                    </li>
                                {% endfor %}
                      </ul>
                    </div>
                  </div>
                  <!-- END sidebar-box -->

                </div>
                    <!-- END sidebar -->

          </div>
        </div>
      </section>
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post {% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }} by e-mail</h1>
        <form method="post">
        {% for field in form %}
            <div class="form-group">
                {{ field.errors }}
                {{ field }}
            </div>
        {% endfor %}
            {% csrf_token %}
            <input class="btn btn-secondary" type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}
    